export const STAGES = [
  ["input", "입력"],
  ["understanding", "상품 이해"],
  ["routing", "HS2 라우팅"],
  ["classification", "분류"],
  ["taric", "TARIC 분기"],
  ["document", "서류 패키지"],
];

export const EVENT_STAGE_LABELS = {
  Pipeline: "파이프라인",
  Input_Intake: "입력 수집",
  Evidence_Intake_Component: "증거 적재",
  Product_Intake: "상품 입력",
  Product_Understanding_Component: "상품 이해",
  Product_Understanding: "상품 이해",
  ProductUnderstanding: "상품 이해",
  HS2_Routing_Component: "HS2 라우팅",
  Regulatory_Domain_Routing: "규제 도메인 라우팅",
  Domain_Router: "도메인 라우팅",
  Regulatory_Domain: "도메인 라우팅",
  Classification: "분류",
  Classification_Component: "분류",
  Document_Component: "문서 패키지",
  Document_Recommendation: "문서 패키지",
};

export const PRODUCT_FACT_KEYS = [
  "product_name",
  "url",
  "intended_use",
  "origin_country",
  "source_urls",
];

export const RECONSTRUCTION_KEYS = [
  "mode",
  "used_llm_reconstruction",
  "fallback_reason",
  "error",
  "detail_table_count",
  "classification_fact_count",
  "classification_text_line_count",
];

export const ROUTE_KEYS = [
  "allowed_hs2",
  "blocked_hs2",
  "enforce_hs2_boundary",
  "fallback_allowed",
  "domain_scopes",
  "pre_gate_domains",
  "missing_facts",
  "routing_basis",
  "candidate_chapter_details",
];

export const UNDERSTANDING_KEYS = [
  "product_name",
  "short_description",
  "commercial_identity",
  "translated_product_name",
  "normalized_tariff_description",
  "ingredient_class",
  "food_form",
  "processing_state",
  "identity_terms",
  "product_form_terms",
  "chapter_hint_terms",
  "chapter_hint_status",
  "domain_hints",
  "confidence",
];

export const LABELS = {
  product_name: "상품명",
  description: "설명",
  url: "URL",
  source_urls: "근거 URL",
  intended_use: "상품 용도",
  origin_country: "상품 원산국",
  mode: "복원 방식",
  used_llm_reconstruction: "LLM 복원 사용",
  fallback_reason: "대체 사유",
  error: "오류",
  detail_table_count: "복원 상세표 수",
  classification_fact_count: "구조화 fact 수",
  classification_text_line_count: "정규화 텍스트 줄 수",
  allowed_hs2: "허용 HS2",
  blocked_hs2: "차단 HS2",
  enforce_hs2_boundary: "HS2 경계 강제",
  fallback_allowed: "fallback 허용",
  domain_scopes: "도메인 scope",
  pre_gate_domains: "사전 게이트 도메인",
  missing_facts: "부족 정보",
  routing_basis: "라우팅 근거",
  candidate_chapter_details: "챕터 점수 상세",
  product_id: "Product ID",
  short_description: "짧은 설명",
  commercial_identity: "상업적 식별명",
  translated_product_name: "번역 상품명",
  normalized_tariff_description: "정규화 tariff 설명",
  ingredient_class: "원재료 분류",
  food_form: "식품 형태",
  processing_state: "가공 상태",
  identity_terms: "식별 토큰",
  product_form_terms: "형태 토큰",
  chapter_hint_terms: "챕터 힌트",
  chapter_hint_status: "챕터 힌트 상태",
  domain_hints: "도메인 힌트",
  confidence: "신뢰도",
  total_score: "총점",
  retrieval_sources: "검색 출처",
  matched_keywords: "매칭 키워드",
  score_breakdown: "점수 분해",
  nodes: "코드 노드",
  run_id: "Run ID",
  run_dir: "Run 경로",
  document_package_id: "문서 패키지 ID",
  cn8: "CN8",
  taric10: "TARIC10",
};
